version: '3.7'
#Network
networks:
  app-network:
#data
volumes:
  db-data:
#services
services:
  #database
  app-db:
    image: mysql:8.0.17
    container_name: app-db
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db-data:/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: testdb
    networks:
      app-network:

  app-backend:
    image: springboottestimg
    ports:
      - 1234:4321
    environment:
      DATASOURCE_HOST: app-db
      DATASOURCE_POST: 3306
      DATASOURCE_NAME: testdb
      DATASOURCE_USERNAME: root
      DATASOURCE_PASSWORD: 1234
    networks:
      app-network:



