version: '3.8'
#service group
services:
  #backend server
  app-backend:
    #wait for db up
    depends_on:
      - app-database
    image: springboottestimg
    restart: on-failure
    ports:
      - "8000-8999:4321"
    environment:
      DATASOURCE_HOST: app-database
      DATASOURCE_PORT: 3306
      DATASOURCE_NAME: demoDb
      DATASOURCE_USERNAME: root
      DATASOURCE_PASSWORD: 123456
    networks:
      backend2database:

  #database
  app-database:
    image: mysql:8.0.17
    restart: always
    expose:
      - 3306
    volumes:
      - database-data:/data/mysql
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: demoDb
    networks:
      backend2database:


#network
networks:
  backend2database:
#db data
volumes:
  database-data:


