version: '3.8'
#service group
services:
  #backend server
  app-backend:
    #wait for db up
    depends_on:
      - app-db
    image: springboottestimg
    ports:
      - "8000-8999:4321"
    environment:
      DATASOURCE_HOST: app-db
      DATASOURCE_POST: 3306
      DATASOURCE_NAME: testdb
      DATASOURCE_USERNAME: root
      DATASOURCE_PASSWORD: 1234
    networks:
      backend2database:

  #database
  app-db:
    image: mysql:8.0.17
    container_name: app-db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - database-data:/data/mysql
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: testdb
    networks:
      backend2database:


#network
networks:
  backend2database:
#db data
volumes:
  database-data:


